# Generated by Django 3.2.3 on 2024-02-01 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Название меню",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, verbose_name="Идентификатор"
                    ),
                ),
            ],
            options={
                "verbose_name": "меню",
                "verbose_name_plural": "Меню",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название пункта меню"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255,
                        verbose_name="Название пункта идентификатора",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app_menu.menu",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="childrens",
                        to="app_menu.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "пункт меню",
                "verbose_name_plural": "Пункты меню",
                "ordering": ("id",),
            },
        ),
    ]
